#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2007-04-19

prog=`basename $0`

usage () { echo "usage: $prog [-h] dir"; }

help () {
  cat <<EOF
Run coq_stat on each Coq contribution.

Options:
-h Provide this help and exit
EOF
}

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then usage; exit 1; fi

root=$1

subdirs () { ls -F $dir | grep / | sed 's|/||' | xargs; }

for d in `dir=$root; subdirs`
do
  for e in `dir=$root/$d; subdirs`
  do
    echo $e
    ./coq_stat $root/$d/$e
    echo ""
  done
done
