#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2005-02-03

# start directory

start=`pwd`

# makefile without coq files
# parameters: root subdirs

mkmf () {
  echo create $root/Makefile ...
  sed -e "s|SUBDIRS :=|SUBDIRS := $subdirs|" Makefile.skeleton > $root/Makefile
}

# makefile with coq files
# parameters: Rdir dir

mkcoqmf () {
  echo create $dir/Makefile ...
  cd $dir
  coq_makefile -R $Rdir Rewriting [^\.]*.v > $dir/Makefile
  cd $start
}

# makefiles for a directory and its subdirectories
# parameters: Rdir root subdirs

mkmfsub () {
  for d in $subdirs
  do
    dir=$root/$d; mkcoqmf
  done
}

# Util

root=Util
subdirs='Logic Pair Bool Relation Nat Integer List Vector Polynom Multiset'
mkmf
Rdir=../..
mkmfsub

# Term

root=Term
subdirs='WithArity Varyadic SimpleType'
mkmf
Rdir=../..
mkmfsub

# simple directories

root=$start
subdirs='MannaNess PolyInt DP Filter Conversion MPO RPO HORPO'
Rdir=..
mkmfsub
