#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2005-02-03

set -x

cwd=`pwd`

cd /tmp

rm -rf color
cvs -d :ext:blanqui@scm.gforge.inria.fr:/cvsroot/color co color

dir=CoLoR_`date +%y%m%d`
rm -rf $dir
mv color $dir

rm -rf `find $dir -name CVS -o -name .cvsignore`

tar cf $dir.tar $dir
gzip $dir.tar
mv $dir.tar.gz $cwd

#rm -rf $dir
