#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2006-01-16

doc=`pwd`/doc/main.html

# add an entry for each file of $dir

prfiles () {
  echo "<li>$dir<ul>" >> $doc
  for f in `ls $dir/*.v`
  do
    if test "$root" = ""
    then
      d=$dir
    else
      d=$root.$dir
    fi
    g=`basename $f .v`
    echo "<li><a href=\"Rewriting.$d.$g.html\">$g</a></li>" >> $doc
  done
  echo "</ul></li>" >> $doc
}

# add an entry for each $subdirs of $root

prdir () {
  echo "<li>$root<ul>" >> $doc
  cd $root
  for d in $subdirs
  do
    dir=$d; prfiles
  done
  cd ..
  echo "</ul></li>" >> $doc
}

# begin

cat doc/begin.html > $doc

# Util

root=Util
subdirs='Logic Pair Bool Relation Nat Integer List Vector Polynom Multiset Matrix'
prdir

# Term

root=Term
subdirs='WithArity Varyadic SimpleType'
prdir

# simple directories

root=''
for dir in MannaNess PolyInt MatrixInt DP Filter Conversion MPO RPO HORPO
do
  prfiles
done

# end

cat doc/end.html >> $doc
