#!/bin/sh

output=stat_time.log

echo generate $output ...

echo > $output

for f in `find . -name .\*.time`
do
  echo `echo ${f%.time}.v|sed -e 's|/\.|/|'` `cat $f` >> $output
done

awk -f stat_time.awk $output
