#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2015-03-19

output=stat_time.log

echo generate $output ...

echo > $output

for f in `find . -name \*.time`
do
  echo `echo ${f%.time}.v` `cat $f` >> $output
done

awk -f stat_time.awk $output
