#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2007-04-17

#set -x

lines () {
  wc -l `find $dir -name \*.v` | grep total | sed 's|total||'
}

dir=Util; util=`lines`
dir=Term; term=`lines`
dir=.; total=`lines`

dir=Util/Logic; logic=`lines`
dir=Util/Relation; relation=`lines`
dir=Util/Algebra; algebra=`lines`
math=`expr $logic + $relation + $algebra`

util=`expr $util - $math`

termin=`expr $total - $util - $term`

display () {
  mean=`expr 100 \* $val / $total`
  echo $dir $val $mean%
}

dir=Util; val=$util; display
dir=Term; val=$term; display
dir=Math; val=$math; display
dir=Termin; val=$termin; display
dir=Total; val=$total; display
