#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2007-04-17

#set -x

lines () {
  wc -l `find $dirs -name \*.v` | grep total | sed 's|total||'
}

dirs=Util; util=`lines`
dirs=Term; term=`lines`
dirs=.; total=`lines`

dirs='Util/Logic Util/Relation Util/Algebra'; math=`lines`

util=`expr $util - $math`

termin=`expr $total - $util - $term`

display () {
  mean=`expr 100 \* $val / $total`
  echo $dir $val $mean%
}

dir=Util; val=$util; display
dir=Term; val=$term; display
dir=Math; val=$math; display
dir=Termin; val=$termin; display
dir=Total; val=$total; display
