#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2015-03-19

args=$*
n=$#
shift `expr $n - 1`
f=${1%.v}
/usr/bin/time --quiet -f "%e" -o $f.time coqc $args
cat $f.time
