#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2005-02-03

set -x

cwd=`pwd`
dir=CoLoR_`date +%y%m%d`

cd /tmp
rm -rf $dir
cvs -d :ext:blanqui@cvs-sop.inria.fr:/CVS/rewriting co color
mv color $dir

cd $dir
rm -rf `find . -name CVS -o -name .cvsignore`
rm -f `find . -mindepth 2 -name Makefile`
rm -f createDist

cd /tmp
tar cf $dir.tar $dir
gzip $dir.tar
mv $dir.tar.gz $cwd

#rm -rf $dir
