#!/bin/bash

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2005-02-03

# root directory

cwd=`pwd`

# makefile without coq files
# parameters: dir subdirs

mkmf () {
  echo create $dir/Makefile ...
  sed -e "s|SUBDIRS :=|SUBDIRS := $subdirs|" Makefile.skeleton > $dir/Makefile
}

# makefile with coq files
# parameters: dir

mkcoqmf () {
  echo create $dir/Makefile ...
  cd $dir
  coq_makefile -R $Rdir Rewriting [^\.]*.v > Makefile
  cd $cwd
}

# makefiles for a directory and its subdirectories
# parameters: root subdirs

mkmfsub () {
  dir=$root; mkmf
  for d in $subdirs
  do
    dir=$root/$d; Rdir=../..; mkcoqmf
  done
}

# Util

root=Util
subdirs='Logic Pair Bool Relation Nat Integer List Vector Polynom Multiset'
mkmfsub

# Term

root=Term
subdirs='WithArity Varyadic SimpleType'
mkmfsub

# simple directories

Rdir=..
for dir in MannaNess PolyInt DP Filter Conversion MPO RPO HORPO
do
  mkcoqmf
done
