#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2015-03-27

f=${1%.v}
d=`dirname $2`
g=`basename $2 .v`

svn mv $f.v $d/$g.v
for s in vo glob v.d time
do
  mv $f.$s $d/$g.$s
done
