#!/bin/sh

# CoLoR, a Coq library on rewriting and termination.
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2007-04-17

#set -x

lines () {
  wc -l Makefile `find $dir -name \*.v` | grep total | sed 's|total||'
}

dir=Util; data=`lines`
dir=Term; term=`lines`
dir=.; total=`lines`
dir='Util/Logic Util/Relation Util/Algebra'; math=`lines`

data=`expr $data - $math`

termin=`expr $total - $data - $term`

display () {
  mean=`expr 100 \* $val / $total`
  echo $dir $val $mean%
}

dir=Data; val=$data; display
dir=Term; val=$term; display
dir=Math; val=$math; display
dir=Termin; val=$termin; display
dir=Total; val=$total; display

echo ""

files=`find . -name \*.v`

number () {
  echo $key `grep $key $files | wc -l`
}

key=Inductive; number
key=Fixpoint; number
key=Definition; number
key=Lemma; number
