# following https://github.com/coq-community/docker-coq-action

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:

  coq:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version: ['8.20.1', '8.19.2', '8.18.0', '8.17.1', '8.16.1', '8.15.2', '8.14.1']
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-color.opam'
          ocaml_version: '4.14.2' # https://hub.docker.com/r/coqorg/coq
          coq_version: ${{ matrix.coq_version }}

  rocq:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rocq_version: [dev, '9.0']
    container:
      image: rocq/rocq-prover:${{ matrix.rocq_version }}
    steps:
      - uses: actions/checkout@v4
      - run: opam install -y .
