# following https://github.com/coq-community/docker-coq-action

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:

  make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version: [dev, '9.0', '8.20', 8.19, 8.18, 8.17, 8.16]
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-color.opam'
          coq_version: ${{ matrix.coq_version }}
