# following https://github.com/coq-community/docker-coq-action

name: Docker CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - dev
          - '8.20'
          - '8.19'
          - '8.18'
          - '8.17'
          - '8.16'
          - '8.15'
          - '8.14'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-color.opam'
          coq_version: ${{ matrix.coq_version }}
